export const gyerekLeiro = {
  gyerek_taj: {
    megjelenes: "Tajszám",
    tipus: "number",
    value: "",
    regex: "",
    validalas: "",
  },
  vez_nev: {
    megjelenes: "Vezeték név",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  ker_nev: {
    megjelenes: "Kereszt név",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  szul_datum: {
    megjelenes: "Születési dátum",
    tipus: "date",
    value: "",
    regex: "",
    validalas: "",
  },
  szul_hely: {
    megjelenes: "Születési hely",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  lakcim_varos: {
    megjelenes: "Lakhely",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  lakcim_irSzam: {
    megjelenes: "Irányitószám",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  lakcim_utca: {
    megjelenes: "Utca",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
};

export const reszletesAdatok = {
  adatok: {
    gyerek_taj: {
      megjelenes: "Tajszám",
      tipus: "number",
      value: "",
      regex: "",
      validalas: "",
    },
    vez_nev: {
      megjelenes: "Vezeték név",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    ker_nev: {
      megjelenes: "Kereszt név",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    szul_datum: {
      megjelenes: "Születési dátum",
      tipus: "date",
      value: "",
      regex: "",
      validalas: "",
    },
    szul_hely: {
      megjelenes: "Születési hely",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    lakcim_varos: {
      megjelenes: "Lakhely",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    lakcim_irSzam: {
      megjelenes: "Irányitószám",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    lakcim_utca: {
      megjelenes: "Utca",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    erzekenyseg: {
      megjelenes: "Érzékenység",
      tipus: "",
      value: "",
      regex: "",
      validalas: "",
    },
  },
  szulo_adatok: {
    vez_nev: {
      megjelenes: "Vezeték név",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    ker_nev: {
      megjelenes: "Kereszt név",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    telefonszam: {
      megjelenes: "Telefonszám",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    lakcim_varos: {
      megjelenes: "Lakhely",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    lakcim_irSzam: {
      megjelenes: "Irányitószám",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    lakcim_utca: {
      megjelenes: "Utca",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    felhasznalo_nev: {
      megjelenes: "Felhasználó név",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    felhasznalo_email: {
      megjelenes: "Felhasználó email",
      tipus: "email",
      value: "",
      regex: "",
      validalas: "",
    },
  },
  beadott_oltas: {
    oltas_tipus: {
      megjelenes: "Oltás tipus",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    oltoanyag_neve: {
      megjelenes: "Oltás neve",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    beadas_datum: {
      megjelenes: "Beadás dátuma",
      tipus: "date",
      value: "",
      regex: "",
      validalas: "",
    },
    ker_nev: {
      megjelenes: "Orvos kereszt neve",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    vez_nev: {
      megjelenes: "Orvos vezeték neve",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    megjegyzes: {
      megjelenes: "Megjegyzés",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
  },
  beadando_oltas: {
    oltas_tipus: {
      megjelenes: "Oltás tipus",
      tipus: "text",
      value: "",
      regex: "",
      validalas: "",
    },
    ev: {
      megjelenes: "Év",
      tipus: "number",
      value: "",
      regex: "",
      validalas: "",
    },
    honap: {
      megjelenes: "Honap",
      tipus: "number",
      value: "",
      regex: "",
      validalas: "",
    },
    hanyadik: {
      megjelenes: "Hanyadik",
      tipus: "number",
      value: "",
      regex: "",
      validalas: "",
    },
    beadott: {
      megjelenes: "Beadás",
      tipus: "input",
      value: "",
      regex: "",
      validalas: "",
    }
  }
};

export const keszletLeiro = {
  tipus_elnev: {
    megjelenes: "Oltás neve",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  darab: {
    megjelenes: "Darab száma",
    tipus: "number",
    value: "",
    regex: "",
    validalas: "",
  },
  beszerzes_datuma: {
    megjelenes: "Beszerzés dátuma",
    tipus: "date",
    value: "",
    regex: "",
    validalas: "",
  },
  lejarati_datuma: {
    megjelenes: "Lejárati dátuma",
    tipus: "date",
    value: "",
    regex: "",
    validalas: "",
  },
  oltoanyag_neve: {
    megjelenes: "Oltoanyag neve",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  megsemmisitett_datum: {
    megjelenes: "Megsemmisités dátuma",
    tipus: "date",
    value: "",
    regex: "",
    validalas: "",
  },
};

export const ujBeteg = {
  szulo_adatok: {
    email: {
      megjelenes: "E-mail cím",
      tipus: "email",
      value: "",
      placeholder: "email cím",
      regex: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
      validalas: "Nem megfelelő email cim",
    },
  },
  gyerek_adatok: {
    szemelyes_adatok: {
      gyerek_taj: {
        megjelenes: "Gyerek tajszám",
        tipus: "number",
        value: "",
        regex: /^\d{9}$/,
        validalas: "9 számot kell tartalmaznia!",
      },
      vez_nev: {
        megjelenes: "Vezeték név:",
        tipus: "text",
        value: "",
        regex: /^[A-Z].{1,14}$/,
        validalas: "Nagy betűvel kezdődjön!",
        maxLength: 20,
      },
      ker_nev: {
        megjelenes: "Kereszt név:",
        tipus: "text",
        value: "",
        regex: /^[A-Z].{1,14}$/,
        validalas: "Nagy betűvel kezdődjön!",
        maxLength: 20,
      },
      szul_datum: {
        megjelenes: "Születési dátum:",
        tipus: "date",
        value: "",
        regex: "",
        validalas: "Nem lehet nagyobb mint a mai dátum és kisebb mint 18 év!",
      },
      szul_hely: {
        megjelenes: "Születési hely:",
        tipus: "text",
        value: "",
        regex: /^[A-Z].{2,19}$/,
        validalas: "Minimum 3 és maximum 20 karakter lehet!",
        maxLength: 20,
      },
      erzekenyseg: {
        megjelenes: "Érzékenység (Nem kötelező!):",
        tipus: "textarea",
        maxLength: 400,
      },
    },
    lakcim: {
      lakcim_varos: {
        megjelenes: "Város:",
        tipus: "text",
        value: "",
        regex: /^[A-Z].{2,19}$/,
        validalas: "Minimum 3 és maximum 20 karakter lehet!",
        maxLength: 20,
      },
      lakcim_irSzam: {
        megjelenes: "Irányítószám:",
        tipus: "number",
        value: "",
        regex: /^\d{4}$/,
        validalas: "4 számot kell tartalmaznia!",
      },
      lakcim_utca: {
        megjelenes: "Utca",
        tipus: "text",
        value: "",
        regex: /^[A-Z].{2,19}$/,
        validalas: "Minimum 3 és maximum 20 karakter lehet!",
        maxLength: 20,
      },
    },
  },
};

export const ujBeadott = {
  beadas_datuma: {
    megjelenes: "Beadás dátuma:",
    tipus: "date",
    value: "",
    placeholder: "",
    regex: "",
    validalas: "",
  },
  megjegyzes: {
    megjelenes: "Megjegyzés",
    tipus: "text",
    value: "",
    placeholder: "",
    regex: "",
    validalas: "",
  },
}
