export const gyerekLeiro = {
  tajszam: {
    megjelenes: "Tajszám",
    tipus: "number",
    value: "",
    regex: "",
    validalas: "",
  },
  vez_nev: {
    megjelenes: "Vezeték név",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  ker_nev: {
    megjelenes: "Kereszt név",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  szul_datum: {
    megjelenes: "Születési dátum",
    tipus: "date",
    value: "",
    regex: "",
    validalas: "",
  },
  szul_hely: {
    megjelenes: "Születési hely",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  lakcim_varos: {
    megjelenes: "Lakhely",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  lakcim_irSzam: {
    megjelenes: "Irányitószám",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
  lakcim_utca: {
    megjelenes: "Utca",
    tipus: "number",
    value: "",
    regex: "",
    validalas: "",
  },
  erzekenyseg: {
    megjelenes: "Érzékenység",
    tipus: "text",
    value: "",
    regex: "",
    validalas: "",
  },
};
