export const tesztAdatok = {
  gyerekek: {
    gyerek1: {
      vez_nev: "Jozsef",
      ker_nev: "Attila",
      lakcim_varos: "Szennylőrinc",
      lakcim_irSzam: "7940",
      lakcim_utca: "Rántott utca 2",
      erzekenyseg: "",
      szul_datum: "2010-02-12",
      szul_hely: "Pécs",
    },
    gyerek2: {
      vez_nev: "Gáspár",
      ker_nev: "János",
      lakcim_varos: "Bukarest",
      lakcim_irSzam: "7532",
      lakcim_utca: "Zsákos utca 2",
      erzekenyseg: "laktózérzékeny",
      szul_datum: "2011-05-23",
      szul_hely: "Budapest",
    },
  },
  szulok: {
    szulo1: {
      ker_nev: "Gyozo",
      vez_nev: "Sanyi",
      szemelyi_igazolvany_szam: "453453RE",
      lakcim_varos: "Szennylőrinc",
      lakcim_irSzam: "7940",
      lakcim_utca: "Rántott utca 2",
      felhasznalo_nev: "sdfjs",
      email_cim: "fnsdgjksd@gmail.com",
    },
    szulo2: {
      ker_nev: "MaroBrando",
      vez_nev: "Radiátor",
      szemelyi_igazolvany_szam: "453434RE",
      lakcim_varos: "Bukarest",
      lakcim_irSzam: "7532",
      lakcim_utca: "Zsákos utca 2",
      felhasznalo_nev: "sddfgdfgfjs",
      email_cim: "fnsdgjdfgdksd@gmail.com",
    },
  },
};
